name: howth_golf_live
description: Live golf tournament score card.

version: 4.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: 0.13.4
  firebase_auth: 0.15.4
  meta: 1.1.8
  provider: 4.1.2
  tuple: 1.0.3
  connectivity: 0.4.8+6
  shared_preferences: 0.5.7+3
  test: 1.14.4
  flutter_svg: 0.17.4

  bubble_tab_indicator: 0.1.4
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: 1.0.0
  flutter_rounded_date_picker: 1.0.4
  animations: 1.0.0+5
  showcaseview: 0.1.5

dev_dependencies:
  flutter_launcher_icons: 0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: lib/assets/fonts/CormorantGaramond-BoldItalic.ttf
    - family: FiraSans
      fonts:
        - asset: lib/assets/fonts/FiraSans-Regular.ttf
  assets:
    - lib/assets/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/icon/icon.png"
  image_path_android: "lib/assets/icon/icon.png"
  adaptive_icon_background: "lib/assets/icon/background.png"
  adaptive_icon_foreground: "lib/assets/icon/foreground.png"
