name: howth_golf_live
description: Live golf tournament score card.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.5+1
  firebase_auth: 0.15.4
  meta: ^1.1.8
  provider: ^4.0.4
  connectivity: ^0.4.8+2
  shared_preferences: ^0.5.3+1
  test: ^1.6.1
  flutter_svg: 0.17.3+1

  bubble_tab_indicator: ^0.1.4
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: 8.4.0
  datetime_picker_formfield: 1.0.0
  flutter_rounded_date_picker: 1.0.3
  animations: ^1.0.0+5
  showcaseview: ^0.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: lib/assets/fonts/CormorantGaramond-BoldItalic.ttf
    - family: FiraSans
      fonts:
        - asset: lib/assets/fonts/FiraSans-Regular.ttf
  assets:
    - lib/assets/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/icon/icon.png"
  image_path_android: "lib/assets/icon/icon.png"
  adaptive_icon_background: "lib/assets/icon/background.png"
  adaptive_icon_foreground: "lib/assets/icon/foreground.png"
