name: howth_golf_live
description: Live golf tournament score card.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.5+1
  meta: ^1.1.8
  shared_preferences: ^0.5.3+1
  test: ^1.6.1
  uuid: 2.0.4

  bubble_tab_indicator: ^0.1.4
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: 8.4.0
  datetime_picker_formfield: 1.0.0
  numberpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: lib/assets/fonts/Cormorant_Garamond/CormorantGaramond-BoldItalic.ttf
    - family: FiraSans
      fonts:
        - asset: lib/assets/fonts/Fira_Sans/FiraSans-Regular.ttf
  assets:
    - lib/assets/
