name: howth_golf_live
description: Live golf tournament score card.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.9.13+1
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  bubble_tab_indicator: ^0.1.4
  cupertino_icons: ^0.1.2
  flutter_spinkit: "^3.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
    - images/